version: '3'

networks:
  default:
    external:
      name: heavenDB
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - heavenApp